### ISSUE TITLE
No XML encryptor configured

### ISSUE THREAD

**Issue by rocklan** [mhdejonge/Terryberry.DataProtection.MongoDb#1]
Thanks for the code! Works great. However, I am getting the following warning:

```No XML encryptor configured. Key ... may be persisted to storage in unencrypted form.```

I've spent a while trying to add some logic to encrypt and decrypt it using AES but couldn't get anything to work, if you have any suggestions I'm all ears.

**Comment by mhdejonge** [comment]
The extension methods in this library just set the XML repository. Which tells asp.net where to write keys to.
I imagine something like the following would solve your warning.
```
services.AddDataProtection()
        .PersistKeysToMongoDb(...)
        .ProtectKeysWithCertificate(...);
```
or
```
services.AddDataProtection()
        .PersistKeysToMongoDb(...)
        .AddKeyManagementOptions(options =>
        {
            IXmlEncryptor encryptor = anyIXmlEncryptor;
            options.XmlEncryptor = encryptor;
        });
```
